language: python
python:
  -"2.7"
  -"3.5"

# command to install dependencies
install: 
	- pip install --upgrade setuptools
	- pip install astroquery astropy
# command to run tests
script: py.test dsfp
